### ISSUE TITLE
Remove generated grapher steps with no modifications

### ISSUE THREAD

**Issue by Marigold** [owid/etl#1152]
We have tons of grapher steps that follow exactly the same template. They just copy garden dataset to grapher. Instead of having hundreds of almost identical grapher steps there, we could generate the default template on the fly if we see `data://grapher/...` step in DAG.

@pabloarosado do you think it's a useful cleanup or is it better to have them explicitly there?

**Comment by pabloarosado** [comment]
Hi @Marigold, I suppose you could extend this criterion to some meadow and garden steps as well. But I think it's useful to have the step file in the corresponding version folder. Otherwise, there will be things in the dag that do not correspond to any existing step. Maybe we could simplify the redundant code, but I'm not sure if removing the files entirely is a good idea.

**Comment by Marigold** [comment]
Thanks for your opinion. I'll go with it and keep the files there. Gonna keep this open and wait until it gets closed automatically.

**Comment by danyx23** [comment]
It looks like we don't have a particular desire right now to change this. Let's revisit it again in the future.
