### ISSUE TITLE
bug: snapshot description gets appended to dataset description

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#1458]
So I’ve seen this behaviour where the snapshot description is appended to the dataset's description. I've seen this in the war datasets I have been importing lately.

For instance, this one:
- Garden: https://github.com/owid/etl/tree/master/etl/steps/data/garden/war/2023-06-22
- Grapher: https://github.com/owid/etl/blob/master/etl/steps/data/grapher/war/2023-06-26/ucdp.py

This is the dataset on admin. In the `Description` field, the text after “ More details about Georeferenced Event Dataset version 23.1 by the UCDP:” has been appended.

From what I learned, a [logic](https://github.com/owid/etl/blob/master/etl/grapher_helpers.py#L350-L360) that appends source description to dataset description (that was a hack).

This text is shown in the sources tab of the charts.

**Comment by Marigold** [comment]
Let me go through how the wicked logic currently works:
1. In meadow step, the line `ds_meadow = create_dataset(dest_dir, tables=tables, default_metadata=snap.metadata)` **creates dataset's source** from snapshot metadata (snapshot's description -> source's description)
2. In the garden step, you overwrite dataset description, but source remains there
3. Right before dataset is upserted to DB, [this code](https://github.com/owid/etl/blob/master/etl/grapher_helpers.py#L389-L399) **concatenates dataset description with source description**

So to be precise, rather than "snapshot description gets appended to dataset description", it's "snapshot description **becomes source description** which gets appended to dataset description".

This is obviously very confusing and was caused by our DB schema and single-source policy. It should be more transparent with origins.

You can fix it by adding `ds_grapher.metadata.sources[0].description = ""` right after creating a grapher dataset.

**Comment by pabloarosado** [comment]
Thanks @Marigold for the clarification. This has been an issue for a long time, but given that this is fixed for new datasets with origins, for now @lucasrodes can do the trick you suggested on the affected datasets.
