### ISSUE TITLE
Sources are not removed when importing to grapher

### ISSUE THREAD

**Issue by Marigold** [owid/etl#147]
Running `etl grapher://... --grapher` automatically creates all objects in grapher. Dataset and variables are upserted correctly on re-running, but if we make any modification to Source, a new one gets created and added to a dataset instead of replacing the old one (we end up with two sources with the same `datasetId`). This is confusing especially since Admin UI shows only the first dataset (the one that we thought is being replaced).

Current workaround involves removing sources manually from DB which is prone to error. We could delete all related sources autmoatically on every `--grapher` run, but we risk losing manual updates to those sources.

**Comment by larsyencken** [comment]
## Technical notes

After discussion, it should be safe to delete sources precisely because manual updates are disabled by default for any data that comes from the ETL.

But.... can we do it without deleting variables too?

```
# foreign key relationships
data values -> variables -> sources -> datasets
```

The problem with deleting and wiping everything is that people will have made nice charts with the variables, so we should not attempt to delete them or change their ids.

## Possible solution

- We merge all sources into one single Source when adding to grapher
- When updating a source, there should be just one; we simply overwrite all its fields
