### ISSUE TITLE
Support for daily data that would replace `yearIsDay`

### ISSUE THREAD

**Issue by Marigold** [owid/etl#1477]
There's a legacy grapher hack with `yearIsDay` and `zeroDay` where you convert your dates to integers, pretend they're years and push to Grapher.

Since we're no longer constrained by `data_values` table in MySQL and instead serve data from S3 as JSON ([example](https://api.ourworldindata.org/v1/indicators/539022.data.json)), we could get rid of `yearIsDay` and `zeroDay` and infer whether we use year or date in grapher.

An alternative would be to keep using `yearIsDay`, but determine it automatically when upserting to MySQL / creating JSON files.

Open questions:
1. Should we keep calling it `year` even though it can contain `dates`? (This is a question for both ETL and owid-grapher)

**Comment by lucasrodes** [comment]
At the moment, we can't really have daily indicators together with yearly indicators in a dataset.

This is because all indicators in a dataset share the same time index. This time index can be either (i) a year or (ii) the number of days since X.

Makes me think of the idea of having time indices for each indicator. Probably that's an overkill at the moment, but we could think of something like this.

**Comment by lucasrodes** [comment]
Triage: Not many datasets need this, and it is unclear what is the best approach.
