### ISSUE TITLE
Dataset Origins are not propagated in create_dataset without `default_metadata`

### ISSUE THREAD

**Issue by Marigold** [owid/etl#1515]
We used to have the following pattern

```
ds_meadow = paths.load_dataset("...")
...
ds_garden = create_dataset(dest_dir, tables=[tb], default_metadata=ds_meadow.metadata, check_variables_metadata=True)
```
We recently got rid of `default_metadata=ds_meadow.metadata` by default assuming nothing's gonna change. The problem is that not using `default_metadata` does not preserve `origins` saved in dataset metadata (only origins on variable level are saved).

Should we even allow origins on the dataset level? They can be currently defined explicitly and right before upserting to MySQL we move dataset origins to all its variables (dataset itself doesn't have an origin in MySQL). It's there only for the matter of convenience, it wouldn't be even needed if we could propagate origins from snapshot to grapher without defining them in YAML file.

@pabloarosado what do you think?

**Comment by pabloarosado** [comment]
As discussed before, a simple solution is to keep `default_metadata`. The main reason for it is to keep `dataset.title`, `dataset.description`, and `dataset.update_period_days` from the previous step.

However, `origins` and `licenses` should be taken not from the previous dataset, but from the variables in the tables (as it happens when `default_metadata` is not given).
