### ISSUE TITLE
metadata: Ensure origins are propagated on steps that used `to_table_metadata()`

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#1700]
After removing `origins` from `DatasetMeta`, now neither tables nor datasets have origins. This means that `snap.to_table_metadata()` doesn't have origins. Therefore, when this function is used (in various meadow steps), we need to ensure that also `origin` is passed. Otherwise, the indicators in the resulting table will have no origins.

**Comment by Marigold** [comment]
@pabloarosado let me know if you need help. I didn't realise we might be using `.to_table_metadata()` outside `snap.read` method.

We have a few options for how to pass the origin:

1. Pass it explicitly as `pr.read_csv(snap.path, metadata=snap.to_table_metadata(), origin=snap.origin)`
2. Pass `SnapshotMeta` instead of `TableMeta` as `pr.read_csv(snap.path, snapshot_metadata=snap.metadata)`
3. Add `origins` to `Table` class (this would be similar to what we had before, but it would be somehow "hidden" from users)

I guess it doesn't matter much whether we choose 1 or 2, most steps load data using snapshot methods anyway.

**Comment by Marigold** [comment]
We went with the first option that explicitly passes origin. It's not perfect, but it works.
