### ISSUE TITLE
metadata: Discourage the use of `display.name` in ETL metadata

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#1903]
### One-liner
We should discourage the use of `display.name` in ETL metadata.

### Context & details
Recently we changed the metadata guidelines so that `display.name` becomes "The public title of an indicator". However, in grapher, this field is often used as "The short display of an indicator inside a chart" (for simplicity, let's call it a "legend"). These are two very different uses of the same metadata field. For example, in [this chart](https://owid.cloud/admin/charts/4246/edit), we need the first indicator to be shown as simply "Agriculture" in the context of the chart, but elsewhere as "Per capita nitrous oxide emissions from agriculture", which is much more informative.

The definition of metadata fields should be:
* Clear: The data scientist should know what a field means and where it will appear, to avoid unexpected public appearances of non-sensical variable titles and descriptions.
* Convenient: Creating metadata takes a lot of time, so we need a good fallback logic to save data scientists' time.

We need to find a trade-off between clarity and convenience.

#### Current situation:
Public appearances of an indicator's main information (NOTE: I'm not totally sure if the following is true):
* **Search result**: `[title_public > grapher_config.title > display.name > title] - [title_variant] - [description_short]`.
  * NOTE: This is currently not true, but I suppose we are moving in the direction of eventually showing description short.
* **Data page title**: `[title_public > grapher_config.title > display.name > title] - [attribution_short] - [title_variant]`.
* **About this data (in a data page and in sources tab)**: `[display.name > title] - [description_short]`.
* **Table tab**: `[display.name > title]`.
* **Heading of a 1-indicator chart**: `[grapher_config.title > display.name > title] - [grapher_config.subtitle > description_short]`.
* **Legend in a chart**: `[display.name > title]`.
* **Admin page**: `[title]`.

PROS:
* Nothing to do, we have already adopted this workflow.
* It lets us have a data page with a title that is different from the chart title or the indicator's public title.
  * We probably won't need this often.

CONS:
* The field `title_public` is almost never used (given that `display.name` is much more versatile).
  * For an indicator with dimensions, one can just define `display.name` and `title_variant`. One would only define `title_public` if the title of the data page needs to be different from the title of the chart or the title of the indicator.
* We don't have any field to define the legend of an indicator, in a chart or an indicator-based explorer, from the ETL metadata (e.g. to replace "Per capita nitrous oxide..." by simply "Agriculture"). To achieve that, you need to manually modify `display.name` in the chart admin or in the explorer tsv file.
* If you define `display.name` to be a short legend for an indicator (e.g. "Agriculture"), we don't want this short legend to appear elsewhere in the sources tab, next to the `title_variant` and `description_short`. This leads to incomplete information, e.g. "Agriculture: Measured in million tonnes." (keep in mind that `description_short` is meant to **accompany** the indicator's title, not replace it). See an example of this issue on the sources tab of [this chart](https://owid.cloud/admin/charts/4246/edit).

NOTE: I think Alternative 1 here doesn't bring much value, so I'll skip it entirely:
~#### Alternative 1 (minimal changes):~
~* We keep everything exactly in the same way.~
~* We discourage people from using `display.name`, and encourage them to use `title_public` instead.~
  ~* The only situation where `display.name` should be used is when having an indicator with multiple dimensions. In that case, `display.name` should be a human-readable version of `title`, that contains all dimensions.~

~PROS:~
~* Nothing to change in the code (although it would be appropriate to refactor recent uses of `display.name`).~
~* It lets us have a data page with a title that is different from the chart title or the indicator's public title.~
  ~* We probably won't need this often.~

~CONS:~
~* We don't have any field to define the legend of an indicator, in a chart or an indicator-based explorer, from the ETL metadata (e.g. to replace "Per capita nitrous oxide..." by simply "Agriculture"). To achieve that, you need to manually modify `display.name` in the chart admin or in the explorer tsv file.~
~* (same issues a above) If you define `display.name` to be a short legend for an indicator (e.g. "Agriculture"), we don't want this short legend to appear elsewhere in the sources tab, next to the `title_variant` and `description_short`. This leads to incomplete information, e.g. "Agriculture: Measured in million tonnes." (keep in mind that `description_short` is meant to **accompany** the indicator's title). See an example of this issue on the sources tab of [this chart](https://owid.cloud/admin/charts/4246/edit).~

#### Alternative 2:
Public appearances of an indicator's main information:
* **Search result**: `[title_public > grapher_config.title > title] - [title_variant] - [description_short]`.
* **Data page title**: `[title_public > grapher_config.title > title] - [attribution_short] - [title_variant]`.
* **About this data (in a data page and in sources tab)**: `[title_public > grapher_config.title > title] - [title_variant] - [description_short]`.
* **Table tab**: `[title_public > title] - [title_variant]`.
* **Heading of a 1-indicator chart**: `[grapher_config.title > title_public > title] - [grapher_config.subtitle > description_short]`.
  * NOTE: Here we reverse the hierarchy of `grapher_config.title` and `title_public`. This can be confusing, but this way we don't need to define both `title_public` and `grapher_config.title` for indicators with long names. And it also lets us have a data page with a title different from the chart title.
* **Legend in a chart**: `[display.name > title_public > title]`.
* **Admin page**: `[title]`.

PROS:
* The definitions of the different fields become clearer:
  * `title_public` is the replacement of the indicator's title, and goes together with `title_variant` and `description_short`.
  * `display.name` is the name of the indicator used in legends.
  * `grapher_config.title` is the chart title.
* You can define legends from ETL metadata.

CONS:
* We need some refactoring in the grapher sources tab and data page code, to ensure that `display.name` is only used in legends.
* The simple hierarchy `title_public > grapher_config.title > title` is not always fulfilled. But we don't really need it, as long as we understand and agree with the fallbacks.
* We need to check if this change affects other charts (mostly in the work of the last few weeks).
* We need to change the guidelines, which can cause some short-term confusion.
* We don't have the option to have a data page title different from the indicator's public name.
  * I don't know if this will ever be a very important requirement, but if we think it is, then we should stick to `display.name`.

**Comment by lucasrodes** [comment]
Thoughts on Alternative 1:

> We discourage people from using display.name, and encourage them to use title_public instead.

As mentioned during the discussion and my previous message, I currently need to use both. `title_public` usually lacks dimensions (I put these in `title_variant`), and the indicator name in the 'about' or 'table' sections shouldn't lack the dimension.

**Comment by lucasrodes** [comment]
> I think what you are pointing out is an issue with the table and sources tabs, rather than a justification to keep using display.name. If we could show title_public - title_variant in the table and sources tab, then you wouldn't need to use display.name, right?

Agree. But I think that this change is not considered in the current situation or in alternative 1, but only in alternative 2 (3rd and 4th point). Therefore, I'd still need `display.name` in these first situtations.

**Comment by pabloarosado** [comment]
You're right. I've just added a note to Alternative 1. To be fair, I don't think Alternative 1 is very useful, it's pretty much exactly what we have now, just that "we try to avoid `display.name` when possible".

**Comment by pabloarosado** [comment]
Thanks @spoonerf, that's a great example.
I understand your point that using `display.name` to set a legend from ETL may not be useful when dealing with indicators with many dimensions (and you may have to do it from the chart admin). However, it will still be useful for other simpler indicators.

Regardless of setting the legend (which is not going to be a common practice in any case) the main thing to fix is where `display.name` shows up and how we use it.

Currently, you'll see `display.name` in the sources tab (possibly also in data pages?), e.g. `All Ages` as the indicator's title, followed by its short description. This doesn't make sense. So, to summarize my proposal above (Alternative 2):
1. The field `display.name` should appear only in chart legends (and possibly the table tab? not sure).
2. We should discourage the use of `display.name` as "the public name of the indicator", and use instead `presentation.title_public` and `presentation.title_variant` (especially for multidimensional indicators). The field `display.name` becomes therefore just what appears in chart legends (and possibly the table tab).

Do you agree?

**Comment by spoonerf** [comment]
Thanks @pabloarosado!

Perhaps on 1, `display.name` should appear on the table tab only on multi-indicator charts? 

On 2, I do agree and I will move towards using `presentation.title_public` and `presentation.title_variant` in the future for disaggregations, I am pretty certain now I have been using `display.name` wrongly 😄 

Thanks for thinking this all through so carefully and explaining it so well!

**Comment by pabloarosado** [comment]
Thanks @spoonerf, we all may have been misusing `display.name` in the past few weeks, but we didn't think about these edge cases. Once we decide on this I'll adapt the ETL guidelines. But we'll still need to fix where `display.name` appears in grapher.

@danyx23 to me the conclusion is currently quite clear, and we should adopt "Alternative 2" described above (maybe with some modifications). There are some cons, but I think they are less bad than the current situation, where `display.name` is sometimes the official title of an indicator, and it's short and ambiguous like `Cancer` or `All Ages`.
But maybe there's a better alternative that I haven't considered. What do you think?

During the offsite I expect no ETL steps will be created, but right after that week it would be good to implement the changes, otherwise, the longer we wait, the more misuses of `display.name` we'll have to refactor.

**Comment by larsyencken** [comment]
Catching up here now. It seems that we should let the data pages release go out before tackling this. Then, when we do tackle this, we should update metadata for the recently released data pages where needed.

**Comment by danyx23** [comment]
Thanks for documenting and discussing this, everyone! I think the Alternative 2 propsal makes sense by and large but I think it wouldn't hurt to keep display.name in the fallback chain so that old metadata does not need another code path in Grapher. In Grapher, when showing things like the table header, we want to find the text for this in a coherent way and ideally in a form that does not require us to discern between the schemaVersion of the indicator in question. 

With Alternative 2 we would in any case have to set `title_public`, `title_variant `(and maybe `attribution_short`) on a lot more indicators (basically all that were created in the last two months, or at least those that are rendered as data pages).

I think we don't loose anything if we adapt Alternative 2 in a way that is more backwards compatible - basically instead of going `title_public > grapher_config.title > title` we could just go `title_public > grapher_config.title > display.name > title`. This would mean that old indicators work as before with a single code path. It would also mean that the indicators we created in the last two months can optionally be upgraded to use title_public but if they stay with display.name for the time being that would also be fine. It would also allow us to use title_public in all places going forward as the more specific title to the public and use display.name for the legend only.

I also think that we should not combine `title` with `title_variant `and `attribution_short` as it will be redundant for the title for most cases, no?

#### Alternative 3:
Public appearances of an indicator's main information:
* **Search result**: `[title_public > grapher_config.title > display.name > title] - [title_variant] - [attribution_short] - [description_short]`.
* **Data page title**: `[title_public > grapher_config.title > display.name > title] - [attribution_short] - [title_variant]`.
* **About this data (in a data page and in sources tab)**: `[title_public > grapher_config.title  > display.name > title] - [title_variant] - [attribution_short] - [description_short]`.
* **Table tab**: `[title_public > display.name > title] - [title_variant] - [attribution_short]`.
* **Heading of a 1-indicator chart**: `[grapher_config.title > title_public > display.name > title] - [grapher_config.subtitle > description_short]`.
  * NOTE: Here we reverse the hierarchy of `grapher_config.title` and `title_public`. This can be confusing, but this way we don't need to define both `title_public` and `grapher_config.title` for indicators with long names. And it also lets us have a data page with a title different from the chart title.
* **Legend in a chart**: `[display.name > title_public > title]`.
* **Admin page**: `[title]`.

PROS:
* The definitions of the different fields become clearer:
  * `title_public` is the replacement of the indicator's title, and goes together with `title_variant`, `attribution_short` and `description_short`.
  * `display.name` is the name of the indicator used in legends going forward, but use as the indicator's title for legacy indicators is ok.
  * `grapher_config.title` is the chart title.
* You can define legends from ETL metadata (for simple cases, see Fiona's comments above)
* Works without modifications for indicators with both old and new metadata
* Retrofitting title_public for indicators created between Sept and Nov 2023 is optional, not mandatory

CONS:
* We need some refactoring in the grapher sources tab and data page code, to ensure that `display.name` is only used as the primary field in legends.
* The simple hierarchy `title_public > grapher_config.title > display.name > title` is not always fulfilled. But we don't really need it, as long as we understand and agree with the fallbacks.
* We need to check if this change affects other charts (mostly in the work of the last few weeks).
* We need to change the guidelines, which can cause some short-term confusion.
* We don't have the option to have a data page title different from the indicator's public name.
  * I don't know if this will ever be a very important requirement, but if we think it is, then we should stick to `display.name`.

**Comment by pabloarosado** [comment]
Thanks @danyx23! Your proposed Alternative 3 makes sense. I only see the following caveat: If we define `display.name` to improve a chart legend (like in the "Agriculture" example above), we are forced to also define `title_public`. This is not necessarily a problem, but we may need some way to remind us about it. Otherwise, if we define `display.name` and forget to define `title_public`, we will see "Agriculture" in unwanted places, like search results (instead of "Per capita nitrous oxide emissions from agriculture", which would be the correct title to display).

This could probably be solved by raising a warning if `display.name` is defined without any `title_public`. We could do a small refactor to ensure all indicators with new metadata and a defined `display.name` also have `title_public`.

I'm not sure if this issue may also affect old indicators for which `display.name` is defined, but do not have `title_public`. Wouldn't the `display.name` (e.g. "Agriculture") be shown in unwanted places?

If you think this is not a problem, then Alternative 3 is good to go.

**Comment by Marigold** [comment]
Another option to keep it backwards compatible would be to run a migration that sets `title_public = display.name` for old indicators and go with Alternative 2 (changing this will be a bit more involved in ETL, but doable with a script iterating over all YAML files). That would keep fallback chains a bit simpler.

**Comment by larsyencken** [comment]
This issue became the discussion rather than the spec, so I wrote it up again here: https://github.com/owid/etl/issues/2052

Let's continue from there
