### ISSUE TITLE
ETL freezing on step `data://meadow/climate/2023-12-20/surface_temperature`

### ISSUE THREAD

**Issue by Marigold** [owid/etl#2334]
ETL tends to freeze on step `data://meadow/climate/2023-12-20/surface_temperature`. The snapshot has 1.6gb, so ETL may start swapping memory after decompressing it.

I can't run it locally as the memory spikes and starts swapping. It takes ~3min on @veronikasamborska1994 machine.

**Comment by Marigold** [comment]
@veronikasamborska1994 I looked at the script and couldn't find any way how to make it faster. I tried to optimise memory usage a bit [in this PR](https://github.com/owid/etl/pull/2335/files), but the peak memory usage could still be >20gb (I've seen 40gb of memory on some staging servers). The memory spikes after creating `clip` object.

It takes ~2h to run the step on the server. I don't know why it is so long. It could be memory swapping, but it could be as well something else.

Is such a heavy computation expected? Is there any way to make it faster?

**Comment by veronikasamborska1994** [comment]
@Marigold I'll take a look but there aren't that many ways in which this clipping can be done so I am not sure if I'll be able to improve it much. 

What I could definitely do though is move this processing step to snapshot? Would that help?

**Comment by Marigold** [comment]
> What I could definitely do though is move this processing step to snapshot? Would that help?

That's a great idea! It's definitely easier than figuring out why it is so slow in production.

**Comment by Marigold** [comment]
Also getting this from CI run `ETL - build public datasets (branch)` (I didn't know there's a memory cap for CI or Buildkite agents?)
```
File "/var/lib/buildkite-agent/builds/etl-build-2-15/our-world-in-data/etl-build-public-datasets-branch/etl/steps/data/meadow/climate/2023-12-20/surface_temperature.py", line 77, in run
  clip = da.rio.clip(data.geometry.apply(mapping), data.crs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/lib/buildkite-agent/builds/etl-build-2-15/our-world-in-data/etl-build-public-datasets-branch/.venv/lib/python3.11/site-packages/rioxarray/raster_array.py", line 911, in clip
  cropped_ds = _clip_xarray(
               ^^^^^^^^^^^^^
File "/var/lib/buildkite-agent/builds/etl-build-2-15/our-world-in-data/etl-build-public-datasets-branch/.venv/lib/python3.11/site-packages/rioxarray/raster_array.py", line 214, in _clip_xarray
  cropped_ds = xds.where(clip_mask_xray)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/lib/buildkite-agent/builds/etl-build-2-15/our-world-in-data/etl-build-public-datasets-branch/.venv/lib/python3.11/site-packages/xarray/core/common.py", line 1189, in where
  return ops.where_method(self, cond, other)

numpy.core._exceptions._ArrayMemoryError: Unable to allocate 3.90 GiB for an array with shape (1009, 721, 1440) and data type float32
```

**Comment by larsyencken** [comment]
To my knowledge there's no memory limit for our Buildkite agents, only what we set with `prlimit`.

I think there's two approaches that we can do for high memory cases in general:

- **Pre-reduce the snapshot.** We can run a script manually on a high-memory machine to reduce the data to a manageable size, then snapshot the reduced data instead.
  - If we want to, we can snapshot the both the before and after, but only the reduced after version is actually in our ETL run.
- **Use out-of-core processing.** We can use an out-of-core technique for processing the data, one that still works with limited memory
  - Databases like DuckDB and even Sqlite3 may do more disk-based work, and thus use less memory
  - A data frame library like Polars is not out-of-core, but it's more efficient than Pandas since it does query optimisation (NOTE: probably not useful for this specific case)
  - [Vaex](https://github.com/vaexio/) advertises itself specifically for the out-of-core use case, it appears to do query optimisation like Polars but mmap the file so it's more flexible about paging memory in and out

**Comment by pabloarosado** [comment]
Hey, I've just noticed that on my local machine, the meadow step peaks at 35.7GB or RAM! Then I ran it again with `gc.collect()` right after the clip operation, and memory peaked at 25.9GB. I'd need to repeat the experiment more systematically, but at least that's a possible improvement.

**Comment by pabloarosado** [comment]
I have also tried `clip = da.rio.clip(data.geometry.apply(mapping), data.crs, from_disk=True)`, since `from_disk` is "beneficial when the size of the data is larger than memory". I haven't noticed much difference, but it may help in production.

**Comment by pabloarosado** [comment]
Another way to free up some memory is to delete objects when they are not needed anymore.
```
    ...
    # Select the 't2m' variable from the combined dataset and assign it to 'da'.
    # Convert the temperature values from Kelvin to Celsius by subtracting 273.15.
    da = ERA5_combine["t2m"] - 273.15
    # Free up memory.
    del ds, ERA5_combine
    ...
```

**Comment by Marigold** [comment]
Got fixed by https://github.com/owid/etl/pull/2335. If we still experience problems (e.g. with loading that huge gzip file) we should go with the snapshot approach.
