### ISSUE TITLE
wizard: Issues and improvements for Map Bracketer

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#2915]
### One-liner
Add comments for any issue you find or any suggestion you have for Map Bracketer.

**Comment by paarriagadap** [comment]
Hi! Looks very cool! For now, I have found that when I save one indicator configuration it deletes the content of `explorerSubtitle`. I tried with the `air-pollution` explorer and indicator `900429`:
<img width="1407" alt="image" src="https://github.com/owid/etl/assets/63430031/2f74feb2-fbfb-4f5e-8c12-19dcb0f3328e">

**Comment by pabloarosado** [comment]
Thanks @paarriagadap ! It looks like that explorer has two entries for "explorerSubtitle", which should not happen (or is there any situation where that should be allowed?).

**Comment by paarriagadap** [comment]
@pabloarosado Yes, I found out and edited the post. No, I understand it should never be allowed.

**Comment by lucasrodes** [comment]
I was trying the tool for the new `population and demography` explorer. This new explorer, which is available in `owid-content`, branch `unwpp-update`, uses catalogPath instead of variableId.

The error, which is shown in the image below, seems to come from trying to set column `colorScaleNumericMinValue` as a float.

```
df["colorScaleNumericMinValue"] = df["colorScaleNumericMinValue"].astype(float)
```

<img width="575" alt="image" src="https://github.com/owid/etl/assets/18101289/5885c522-0f7c-4a8c-8999-d9c737a16e02">
