### ISSUE TITLE
Migrate monkeypox from ops to ETL

### ISSUE THREAD

**Issue by Marigold** [owid/etl#3034]
We're updating monkeypox data from [owid-admin-prod](https://github.com/owid/ops/blob/main/templates/owid-admin-prod/crontab#L35) and schedule it with CRON. It's hidden and shouldn't run there, so the best would be migrating it to ETL.

**Comment by larsyencken** [comment]
From triage discussion:

- How should it get run?
  - The data in Github hasn't updated in 2 months -- is it still running?
  - This is super related to #3016, and if we want it in the ETL we should decide the approach there first
  - It's a reasonable candidate for the ETL since it doesn't do scraping
  - It would also be ok to self-update using Github actions, then use the repo as input to the ETL (a `github` step)

- How should we keep the repo CSV up to date
  - Pablo suggested an `external` channel, which exists already; the code there publishes to Github as a side-effect
  - We could put these into the DAG as an explicit target

**Comment by larsyencken** [comment]
Update from @Marigold :

- It's going well, and it's not blocked on the regular updates discussion
- The initial approach is to have a common pipeline for all frequent updates, run daily in Buildkite

**Comment by Marigold** [comment]
Mpox explorer is now powered by dataset from ETL. We still have to [merge changes](https://github.com/owid/etl/pull/3021) that would be committing data to github repo.
