### ISSUE TITLE
Importing the wrong modules when executing various steps

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#319]
I have the following structure:
-`bp/2022-07-14/shared.py`
-`bp/2022-07-14/statistical_review.py`
-`energy/2022-07-20/shared.py`
-`energy/2022-07-20/fossil_fuel_production.py`
And, inside `shared.py` I have some common paths within that particular version (for example, I have a `__file__` that lets me get the path to that specific version). If I run the steps `statistical_review` and `fossil_fuel_production` separately, there is no problem. But if etl runs the two steps one after the other, the second step fails. It seems that the `shared` that it's importing in the second step is the one of the previous step. I think this may be related to [this other small issue](https://github.com/owid/etl/pull/298) we discussed the other day.

**Comment by Marigold** [comment]
We have two options here:
1. Import `shared.py` using full path, i.e. `shared = import_module('etl.steps.data.garden.bp.2022-07-14.shared')`
2. Clean up imported modules after every step

The first one would be inconvenient as we'd lose autocompletion and would have to write `import_module` magic everywhere. The second one is a bit inefficient since some modules wouldn't be cached, but in practice it is **millisecond overhead**. I'd go with the second one, but perhaps there are better options @larsyencken?

**Comment by larsyencken** [comment]
We decided to go with cleaning cached imports after every run, to isolate steps, but if we get another case of this, that we will switch to running each step in its own process to avoid bleeding between them.
