### ISSUE TITLE
Refactor chart revision tool and variable matcher

### ISSUE THREAD

**Issue by Marigold** [owid/etl#325]
[Chart revision suggester](https://github.com/owid/etl/blob/master/etl/chart_revision_suggester.py) and [variable matcher](https://github.com/owid/etl/blob/master/etl/match_variables_from_two_versions_of_a_dataset.py) could be refactored a bit (they were pretty much copied from importers repo).

Suggestions:
* add type hints to chart revision suggester
* simplify DB connection with [context managers](https://github.com/owid/etl/blob/master/etl/grapher_import.py#L343)
* integrate [VariableMatcher](VariableMatcher)?

**Comment by pabloarosado** [comment]
I just tried the script `match_*` and it works well (although the output file argument should be mandatory, which wasn't the case in importers).
However, the `chart_revision_suggester` script does not work (at least) because:
* `simplejson` is not installed.
* `pymysql` are not installed. I would avoid installing `pymysql`, since, in importers, this was always yielding a warning (because pandas prefers `sqlalchemy`). I guess this script should use the default etl connection, as you suggested.
* `USER_ID` in importers used to be taken from the environment variables, but in `etl` it does not exist (at least it's not defined in the `.env.example` file).
