### ISSUE TITLE
Add a streamlit interface to Wizard for anomaly detection

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#3369]
## Rough proposal

- [x] In the Wizard, there is a page for anomaly detection
- [ ] The page should present you with a list of all changed grapher indicators
  - It should read from local disk what indicators are upgrades of other indicators
  - You may optionally ask about any arbitrary ETL path for a grapher indicator
- [x] You click "Detect all anomalies"
- [x] It begins fetches data from the S3 API and finds things whilst you wait
  - It should be interactive speed, i.e. take less than one minute
  - If an indicator is an upgrade, it also detects within the context of the previous indicator
  - (optional) It would be dreamy if they appear one by one whilst you wait
- [x] The anomaly detector tries to return only the few "most important" anomalies
- [x] It stores them in some YAML file or SQLite DB; they're still there if you come back later
- [x] It provides a one-click link for any anomaly that takes you to the indicator (either in a chart, or in the admin)
- [x] There is a button to regenerate them all
- [ ] There is a button to delete them all
- [x] They are ephemeral: when you merge your branch, and your staging server dies, they disappear
  - But you can still manually add something important to "What you should know about this indicator" for its data page

**Comment by lucasrodes** [comment]
Some things that we may add in the future:

- **Hiding anomalies**
  - Each anomaly would have a button "hide anomaly" so that this anomaly is no longer shown
  - This should be done in sync with the filter-panel. A possible solution here is to add a new section to the filter pane which works as a [st.popover](https://docs.streamlit.io/develop/api-reference/layout/st.popover). (idea below)
  ![Image](https://github.com/user-attachments/assets/17c73ff5-e5b7-4b15-99d6-08665555c3bc)
- **AI summary**
  - Optimise how we handle the summaries to avoid unnecessary GPT calls.
- **Checksum detection**
  - We should be able to infer if the anomalies in cache are out of sync (maybe using dataset checksums?)

**Comment by lucasrodes** [comment]
@pabloarosado @Marigold I'll close this for now, since we released a first version of [this already](https://owid.slack.com/archives/C014SGT6W9X/p1730190728397969).

We can track improvements in https://github.com/owid/etl/issues/3436
