### ISSUE TITLE
Grapher steps for FAOSTAT take too long.

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#396]
Executing the grapher steps for FAOSTAT on my local grapher takes several hours, and it will take longer on staging/live.

**Comment by Marigold** [comment]
Looking into faster ways for inserting bulk data into MySQL.

**Comment by pabloarosado** [comment]
Would it be possible to a least have a tqdm bar for the time being?

**Comment by Marigold** [comment]
`tqdm` is non-trivial as you don't know number of tables / columns in advance (we could somehow pass it from `get_grapher_tables`, but the code would get more convoluted which is not what we want given that we're going to be switching from `data_values` to something more reasonable anyway). I've tried to make it fast enough so that you don't need tqdm.
