### ISSUE TITLE
Bug: backported dataset needed for SDG got archived

### ISSUE THREAD

**Issue by Marigold** [owid/etl#492]
## Problem

Someone has archived dataset 334 (OPHI Multidimensional Poverty Index - Alkire and Robles (2016)) which is being used in DAG to create our SDG dataset. Now ETL is failing.

Traceback:

```
raise KeyError(f"no match for dataset {namespace}/{version}/{short_name}")
KeyError: 'no match for dataset None/None/dataset_334_ophi_multidimensional_poverty_index__alkire_and_robles__2016_values'
```

## Solution

~We could unarchive it or just get rid of SDG dataset altogether. We already have an official UN SDG dataset in ETL which works well, though is slightly different from this SDG dataset that matches data in our https://sdg-tracker.org/.~

It turned out SDG datasets got updated, created a PR that reflects that in ETL.

**Comment by larsyencken** [comment]
@danyx23 For your thinking about the content graph, we're getting more of these accidental breakages because someone didn't realise a variable was being used.

It could also be an argument for publishing the ETL's dependency model directly into MySQL, so that we could adjust the admin to disallow archiving the dataset in this case.
