### ISSUE TITLE
Mypy is giving non-deterministic errors

### ISSUE THREAD

**Issue by Marigold** [owid/etl#591]
Users are reporting issues with mypy on their local and in CI:

> I don't know if I'm the only one experiencing this (I think I remember an ETL issue about mypy being random, but I don't know if it's the same thing). Basically, if I run `make test `  I get some times no errors, and some times some random errors on files that have nothing to do with my current work. And I think the same happens when trying to merge to master. I have to re-run the same job multiple times until it stops failing due to some random error (e.g. now [this branch](https://github.com/owid/etl/pull/580)'s build fails because etl/steps/data/meadow/irena/2022-10-20/renewable_power_generation_costs.py:15: error: Module "shared" has no attribute "CURRENT_DIR", which is not true). On my local ETL, I just run make test twice with no errors, and the third time I got an error: etl/steps/data/garden/ihme_gbd/2019/gbd_risk.py:21: error: Too many arguments for "run_wrapper" and some similar ones. Is this happening only to me?

Then

> Yes, that seems to have solved the issue for me too (or maybe it's also a fluke :shrug:). But that doesn't make much sense (at least the thrown error is random). Also, the make test is still random. I just run it again and now I got AssertionError: Cannot find module for gbd_tools.run_wrapper (similar to the previous, but not quite :smile: ). I run it again, same error as in the previous time.  I run it again: no errors.

And then

> Now buildkite complains because AssertionError: Cannot find component 'frame' for 'pandas.core.frame.DataFrame'

I also started getting the same error out of the blue. I've tried upgrading `mypy` and experimented with some flags, but with no luck. Eventually I've made **mypy for steps** optional (returning 0 exit code, but still showing errors) to unblock others.

Should we invest time in fixing mypy or should we make a [switch for pyright](https://github.com/owid/etl/issues/472)? I feel like switching would be beneficial even if there were no errors. Running `make check-typing` takes ~100s locally and in CI. Pyright doesn't have problem with multiple modules with the same name and we could run it only once for the entire codebase (in ~10s).

**Comment by larsyencken** [comment]
We're not getting this issue on any other repos, which makes me think the parallelisation optimisation broke things. I would have preferred to remove parallelism and let CI be slow rather than leave non-deterministic checks and prevent failure.

For future reference, a git bisect and a few retries on each might have been a good angle to try to find the source of this error. 

Another clue is that no other Python repo has this issue, meaning it must be special to the setup of this one.

With all that said, I'm happy to try `pyright` instead. I'll leave some notes on the other issue on what would be good to see if we try it out there.

**Comment by danyx23** [comment]
@larsyencken @Marigold I suggest we chat about this briefly in the next data architecture meeting - it seems that not having to install a node environment to build our otherwise entirely python ETL is quite valuable; that said, we don't want to invest days in trying to fix mypy if pyright would be a relatively quick solution. Probably best to chat about the trade-offs in person.

**Comment by Marigold** [comment]
@danyx23 yeah, let's chat about it. I've already started looking into it and switching to pyright was [surprisingly easy](https://github.com/owid/etl/pull/599) (and reduced type check time from 150s to 12s).

As for node environment - `pip install pyright` automagically installs node in virtualenv if you don't have it globally, so we won't really have to modify any ops scripts or READMEs.

**Comment by Marigold** [comment]
Fixed by switching to pyright.
