### ISSUE TITLE
Don't repack to unwieldy types like Category or Float64 if Table is small?

### ISSUE THREAD

**Issue by Marigold** [owid/etl#679]
Motivated by [Slack discussion](https://owid.slack.com/archives/C02706JNFC6/p1670933860792799)

Categories and Float64 types can be sometimes annoying to work with. An example is
```python
df = pd.DataFrame({"a": ["Cabo Verde", "Cameroon"]}).astype({"a": "category"})
df.a.replace(mapping).sort_values()
```
which unexpectedly sorts values by their category codes and not by their actual values. We could use something like
```python
from pandas.api.types import CategoricalDtype

df = ...
countries = sorted(set(df["countries"]))
df.astype({"country": CategoricalDtype(categories=countries, ordered=True)})
```
but oftentimes it's easier to just convert it to string and work with that.

However, working with categories is essential for reducing memory of large datasets.

@pabloarosado's idea was to
> I think the main issue here is not how to work with categories. The main issue (similar to that horrible one with Float64) is that now we have to be constantly checking the dtypes of our dataframes, because, if it's a str, I have to do this, if it's a category, I have to do that. Python/pandas were supposed to be smart enough to let you not care about these sort of things. One idea that I'm having (maybe it's silly) is to have a Table method .to_df(optimal_dtypes=False) which will do the usual pd.DataFrame(Table) but also ensure that all dtypes are the classical, innocent ones. If optimal_dtypes=False (by default), then categories are converted to str, Int* -> int, Float* -> float. It could also have a reset_index=True by default. Would that make sense?

Implementation wise this would mean adding arguments to `Dataset.add(...)`. The question is whether to use optimal types only if set or by default (or have some logic based on dataframe size).

We should keep in mind that datasets are saved to S3 and increasing their size would make our catalog larger. It'd be also weird to have country as a categorical in one dataset and as a string in a different dataset.

An alternative would be to have helper function `use_sane_types(df)` in datautils repo that would automatically convert those types to reasonable ones. One could then call it right after loading the dataset.

**Comment by pabloarosado** [comment]
I'm not sure if packing tables differently is a good solution. As you point out, now some tables will have certain dtypes, and other tables will have different dtypes. That would actually increase the confusion, and make us even more worried about dtypes, so it feels counterproductive.
I think it's fine if tables have optimal dtypes. But optimal dtypes for storage are not optimal for working. So we could have a method that let us go from optimal-for-storage -> optimal-for-work. My original suggestion was:
`table.to_df(optimal_dtypes=False, reset_index=True)` which, in one line, would take an optimal (for storage) table into an optimal (for work) dataframe. Does this make sense?

**Comment by larsyencken** [comment]
Just to confirm, what do we feel the actual optimal dtypes for working are? Reverting to default Pandas types would mean something like:

- `category` -> `str`
- `intX` -> `int64` ?
- `FloatX` -> `float64`
- `IntX` -> `Int64` ?

When I look at this, I can see two possible benefits:

- Correctness issues for the `FloatX` types (e.g. `Float64`)
  - The `FloatX` -> `floatX` conversion could be done automatically at pack time, to reduce the space for correctness issues, but unfortunately it still wouldn't eliminate them. The only way to do that would be to pack integer columns with NAs to floats instead.

- Fix sorting issues for categories
  - Categories could also be remapped at pack time so that the sort on codes is the same as the sort on values

Downsides:

- Packed operations run faster
- There are some opportunities for using Categories better that might still be in the air, e.g. finding a way to have our cake an d eat it too by using ISO alpha3 codes as category codes for those columns, and shipping both in the data frame

@pabloarosado I feel like I'm missing something on the category sides. Is there other types of friction using that dtype that I'm not aware of?

**Comment by pabloarosado** [comment]
Hi @larsyencken, your mapping of types makes sense.

Regarding category type: There have been several instances where using category types involves more code (you can see, e.g. how many lines of code in [datautils.dataframes](https://github.com/owid/owid-datautils-py/blob/main/owid/datautils/dataframes.py) are devoted to dealing with them). I think fixing the sorting at pack time doesn't solve the issue. If at some point within the data step you need to rename a column, you will need to write additional code if the column is categorical (and if you forget, you may find strange situations).

Regarding int* vs Int*: The only issue I see in working with the good old int* is that integer columns with nans will become floats, as you mentioned. But I prefer this issue rather than all others (like potentially not being able to detect nans, which is absolutely unacceptable behaviour that I hope pandas fixes soon).

**Comment by Marigold** [comment]
@pabloarosado right, I slightly misunderstood you. Having method `table.to_df(optimal_dtypes=False, reset_index=True)` would work well, but since this is not related to `Table` but to pandas types in general, helper function like that `use_sane_types(df)` or something similar could be better.

**Comment by ikesau** [comment]
Does this mean that @Marigold can proceed with a `use_sane_types(df)` implementation, or is further discussion needed?

**Comment by pabloarosado** [comment]
Sure, I think he can proceed, maybe after creating it we decide to rename it or some other minor changes.

**Comment by Marigold** [comment]
@pabloarosado I'm happy to implement it, though I wanted to first ask whether this is something you wanted to do personally (e.g. because you know your special requirements)

**Comment by Marigold** [comment]
Keeping this open a bit longer.
