### ISSUE TITLE
Project: Bake Grapher style data.json files for most columns in ETL

### ISSUE THREAD

**Issue by danyx23** [owid/etl#759]
In 2022 we tried a few ways of serving data from ETL in a way the grapher admin can use it (python api, node api as part of the grapher admin). None of these were really satisfactory. 

What we currently do is that we have Grapher steps at the end of etl that upsert etl columns to the grapher database. In this process, rows are created in the `datasets`, `variables` and `sources` tables so that the metadata of these entities is registered in the DB. At the same time, the data values are upserted into the data_values table. This table is by far the largest part of the grapher MySQL DB, blowing a DB that would be a few hundred MB to over 70 GB. In light of the upcoming work on provisioning staging servers it would be very desirable if we could kill data_values for good and make it much faster to get a full copy of our database running in another instance.

To kill data_values, the data for all backported or fully ETL datasets (at the grapher level of ETL processing steps) has to be transformed into data.json files. The point where we know best what needs to be regenerated is the ETL which track this information on a dataset level granularity. 

This project is then about creating a new export step that could be part of the ETL but it could also be a separate downstream process, that makes the data of a column available as data.json files and stores them in S3. Every variable (=ETL column) in a dataset in a grapher step would have it's own file.

For the admin, the metadata fetching should still happen as before via the grapher admin api that queries Mysql directly. For baking, the metadata would similarly be consumed from mysql directly.

Open questions:

- [ ] Should the S3 bucket be exposed to the public and cached via cloudflare? If no then the baking step would involve copying the data.json files for the used variables to netlify. If yes then we would serve data files from S3 via cloudflare.
- [ ] Can we bake Garden level variables as well? And if so do we want to? This is more of a question of what to use for ids in this case (variable ids are only generated in the grapher step) and if we can assemble enough metadata for these variables from the ETL alone and what to do if there is a data model mismatch (i.e. if the ETL Garden variable has more dimensions than year + entity)
- [ ] Should separate summary statistics be generated as well? These are currently part of the metadata of a variable but for creating them at baking time would mean that the whole data would have to be fetched again which we'd probably like to avoid. At ETL time we will probably have the data loaded into a pandas dataframe already and can just fetch e.g. the set of entities and the time range.

**Comment by Marigold** [comment]
Let me first review what we've done until now

### Hosting static files on S3 instead of Netlify to reduce its bandwidth (and save on Netlify plan)

```mermaid
graph LR

baking --> |sync| S3 -.-> website
baking --> bakedSite/ -.-> website
```


Once we bake all the static files (.json, .png, .svg), **sync them to S3 and remove them from bakedSite/**. This makes Netlify builds much smaller and faster to deploy. Then redirect `/grapher/data/*` to `https://catalog.ourworldindata.org/bake/live/grapher/data/` (which is behind CloudFlare so _fast_).

This is independent on any `data_values` changes (it could keep loading them from `data_values` or load them from S3).

Issue: https://github.com/owid/owid-grapher/issues/1707
PR: https://github.com/owid/owid-grapher/pull/1719/files


### Creating `[variableid].json` files in ETL when publishing a dataset

```mermaid
graph LR

etl[ETL] --> |publish| S3[S3 .json] -.-> website

baking --> bakedSite/ -.-> website
```


In addition to syncing parquet / feather files to S3, we'd also create `[variableid].json` for **every** variable and upload it to S3 with proper `Content-encoding` (gzip?).

We could then remove variables from baking (and S3 sync) and redirect site to our S3 catalog. However, variables baking **isn't bottleneck** and we might still have to sync other types of files to S3 (.png or .svg) to make it smaller (variables data only [make up about 20% of our build size](https://github.com/owid/owid-grapher/issues/1707)).

Potential issues:
1. Performance (either creating JSON files or syncing them to S3)
2. File size (could be ok with good compression)
3. Even with automatic deploys, there might be delays between merging and file appearing on S3

(We could do this either as part of publishing or as part of upserts to grapher... the latter makes more sense as it reduces delays)

### Baking from parquet files instead of `data_values`

```mermaid
graph LR

etl[ETL] --> |publish| S33[S3 .parquet]

S33 --> baking --> bakedSite/ -.-> website
```

(This could play well with the hosting static files on S3 during baking)

We've tried it before and parked this because [baking from remote catalog was slow](https://github.com/owid/owid-grapher/pull/1696#issue-1398034232) (~1h) as there wasn't a good way how to make range requests to S3. That has apparently changed though and Cloudflare R2 has recently added support for both **range requests and Global CDN**. So if we synced our files also to R2 (which was easy and [there's a PR](https://github.com/owid/etl/pull/583)) we could bake from S3 in reasonable time.

An advantage is that we wouldn't have to mess with .json files. On the other hand, R2 is relatively new and we might hit performance issues (or other issues) with it.

## Best option?

We were almost there with R2 & parquet & syncing S3 during baking, but there were problems with DuckDB and range requests. These might have been solved by now... Is it worth testing the performance again? Not sure.

On the other hand, `[variableid].json` approach is easy to implement and is the sure bet unless we run into performance issues. It wouldn't solve the problem with Netlify build size, we'll still have to sync non-data files to S3 during baking. All in all, I think we should go with it and see where it leads us. What do you think @danyx23 ?

**Comment by Marigold** [comment]
@danyx23 would you mind taking a look at my first shot [in this PR](https://github.com/owid/owid-grapher/pull/1867)? If we agree on the general direction I can add tests etc.

**Comment by Marigold** [comment]
Summarising the steps towards the better world without `data_values`:

* [ ] Add `dataPath` and `metadataPath` to `variables` table https://github.com/owid/owid-grapher/pull/1922
* [ ] Refactor baking with polars library https://github.com/owid/owid-grapher/pull/1892
* [ ] Start syncing `data_values` and metadata of **datasets with at least one chart** to S3 https://github.com/owid/etl/pull/778
* [ ] Bake using data JSON files instead of `data_values` https://github.com/owid/owid-grapher/pull/1887
* [ ] Sync **all datasets** to S3
* [ ] Prune large datasets that have been synced from `data_values`
* [ ] Migrate all services that use data_values to use S3 files (covid, importers, chart revisions)
* [ ] Rip out `data_values` (or make it small enough so that we can export them as part of MySQL dump)

**Comment by Marigold** [comment]
Here are some places where `data_values` is used. None of them looks like a major blocker, though updating them to use `dataPath` could be a fair amount of work (mostly validating that they still work).

### ETL
- [backporting](https://github.com/owid/etl/blob/master/backport/backport.py#L209)
- [chart revision suggester](https://github.com/owid/etl/blob/master/etl/chart_revision_suggester.py#L421) (could be replaced by variable statistics)
- [compare](https://github.com/owid/etl/blob/master/etl/compare.py#L269)

### Grapher
- CSV importer
- deleting variable
- country profiles
- exportChartData
- exportDataset

#### analytics
- sync `data_values` to bigquery
